---
title: "p_trust"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis script for "

```{r load libraries}
library(readr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(stats)
library(lme4)
library(dplyr)
library(ez)
library(ltm)
```


## Extract dataframe from csv file and get (mean, sd) or (mean, se) summary

```{r read csv}

setwd("C:/Users/micha/OneDrive/My_GitHub_Repos/robot-x-ar/data/")
form_df <- read_csv("merged_form_data.csv")

######################### get mean and sd (or se) ######################### 
form_df %>%
  group_by(condition) %>%
  get_summary_stats(tlx_ave, type = "mean_sd")


tlx_dims_df <- data.frame(form_df$tlx_mental, form_df$tlx_physical, form_df$tlx_hurried, 
                          form_df$tlx_successful, form_df$tlx_hard, form_df$tlx_insecure)

######################### calculate Cronbach's Alpha with 95% confidence interval ######################### 
cronbach.alpha(tlx_dims_df, CI=TRUE)


```

## Plots

```{r do plotting}

bxp <- ggboxplot(form_df, x = "condition", y = "tlx_ave", add = "jitter", order=c("A", "B", "C", "D"))
bxp
# ggexport(bxp, filename = "tlx_ave.png")

```


## Check assumptions

```{r check assumptions}

######################### check for outliers ######################### 
form_df %>%
  group_by(condition) %>%
  identify_outliers(tlx_ave)

######################### check normality ######################### 
form_df %>%
  group_by(condition) %>%
  shapiro_test(tlx_ave)
ggqqplot(form_df, "tlx_ave", facet.by = "condition")


```


## Fit Model

```{r fit model}

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(data = form_df, dv = tlx_ave, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- form_df %>%
  pairwise_t_test(
    tlx_ave ~ condition, paired = TRUE,
    p.adjust.method = "holm"
    )
pwc


# ##### kruskal-wallis test
# res.kruskal <- form_df %>% kruskal_test(tlx_ave ~ condition)
# res.kruskal
# 
# form_df %>% kruskal_effsize(tlx_ave ~ condition)


```

```{r fit model}

######################### mental #########################  
res.aov <- anova_test(data = form_df, dv = tlx_mental, wid = pid, within = condition)
get_anova_table(res.aov)

######################### physical #########################  
res.aov <- anova_test(data = form_df, dv = tlx_physical, wid = pid, within = condition)
get_anova_table(res.aov)

######################### hurried #########################  
res.aov <- anova_test(data = form_df, dv = tlx_hurried, wid = pid, within = condition)
get_anova_table(res.aov)

######################### successful #########################  
res.aov <- anova_test(data = form_df, dv = tlx_successful, wid = pid, within = condition)
get_anova_table(res.aov)

######################### hard #########################  
res.aov <- anova_test(data = form_df, dv = tlx_hard, wid = pid, within = condition)
get_anova_table(res.aov)

######################### insecure #########################  
res.aov <- anova_test(data = form_df, dv = tlx_insecure, wid = pid, within = condition)
get_anova_table(res.aov)


```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
