---
title: "p_trust"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis script for "

```{r load libraries}
library(readr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(stats)
library(lme4)
library(dplyr)
library(ez)
library(ltm)
```


## Extract dataframe from csv file and get (mean, sd) or (mean, se) summary

```{r read csv}

setwd("C:/Users/micha/OneDrive/My_GitHub_Repos/robot-x-ar/study1/data/questionnaire/")
# rank_df <- read_csv("vis_ranking.csv")
rank_df <- read_csv("vis_ranking_no_pid.csv")

rank_df$condition <- factor(rank_df$condition, levels = c("D", "A", "B", "C"))
rank_df <- rank_df %>%
  mutate(condition = recode(condition, 
                           "A" = "Baseline",
                           "B" = "HumanHorizontal",
                           "C" = "HumanVertical",
                           "D" = "RobotHorizontal"))
rank_df <- rank_df %>%
  mutate(ranking = recode(ranking, 
                           "1" = "1st",
                           "2" = "2nd",
                           "3" = "3rd",
                           "4" = "4th"))


# ######################### get mean and sd (or se) ######################### 
# rank_df %>%
#   group_by(condition) %>%
#   get_summary_stats(ranking, type = "mean_sd")


```

## Plots

```{r do plotting}

bxp <- ggboxplot(rank_df, x = "condition", y = "ranking", add = "jitter")
bxp
# ggexport(bxp, filename = "tlx.png")


p <- ggplot(rank_df, aes(fill=condition, y=pid, x=ranking)) + 
    geom_bar(position="stack", stat="identity") +
  scale_fill_manual(values = c("#83C4CB", "#2C5985", "#ff7f0e", "#2A7B43" ))+
  theme_minimal() +
  labs(y = "# of users per ranking", x = "Ranking") +
  theme(axis.text.x = element_text(hjust = 0.5, size = 18, face = "bold"),
        axis.text.y = element_text(size=18, face="bold"),
        axis.title.x = element_text(size=18, face="bold"),
        axis.title.y = element_text(size=18, face="bold"),
        legend.position = "none")

p

ggsave("ranking.pdf", plot = p, width = 5, height = 5, device = "pdf")


```


## Check assumptions

```{r check assumptions}

######################### check for outliers ######################### 
rank_df %>%
  group_by(condition) %>%
  identify_outliers(ranking)

######################### check normality ######################### 
rank_df %>%
  group_by(condition) %>%
  shapiro_test(ranking)
ggqqplot(rank_df, "ranking", facet.by = "condition")


```


## Fit Model

```{r fit model}

# ######################### Two-way mixed ANOVA test #########################
# res.aov <- anova_test(data = rank_df, dv = ranking, wid = pid, within = condition)
# get_anova_table(res.aov)

res.aov <- rank_df %>% anova_test(ranking ~ condition, wid=pid)
res.aov


# # Compute the analysis of variance
# res.aov <- aov(ranking ~ condition, data = rank_df)
# # Summary of the analysis
# summary(res.aov)

# TukeyHSD(res.aov)


res <- pairwise.t.test(rank_df$ranking, rank_df$condition,
                 p.adjust.method = "holm")
res 


######################### SIG: Pairwise comparisons between trials for each condition #########################  
pwc <- rank_df %>%
  pairwise_t_test(
    ranking ~ condition, paired = TRUE,
    p.adjust.method = "holm"
    )
pwc


# ###### kruskal-wallis test ######
# res.kruskal <- rank_df %>% kruskal_test(ranking ~ condition)
# res.kruskal
# 
# rank_df %>% kruskal_effsize(ranking ~ condition)



```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
