---
title: "p_trust"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis script for "

```{r load libraries}
library(readr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(stats)
library(lme4)
library(dplyr)
library(ez)
library(ltm)
```


## Extract dataframe from csv file and get (mean, sd) or (mean, se) summary

```{r read csv}

setwd("C:/Users/micha/OneDrive/My_GitHub_Repos/robot-x-ar/data/questionnaire/")
emb_df <- read_csv("main_form_cleaned.csv")

######################### get mean and sd (or se) ######################### 
emb_df %>%
  group_by(condition) %>%
  get_summary_stats(emb_ave, type = "mean_sd")


emb_dims_df <- data.frame(emb_df$emb1, emb_df$emb2, emb_df$emb3, 
                          emb_df$emb4, emb_df$emb5, emb_df$emb6)

######################### calculate Cronbach's Alpha with 95% confidence interval ######################### 
# cronbach.alpha(emb_dims_df, CI=TRUE)


```

## Plots

```{r do plotting}

###### embodiment 1 ###### 
bxp <- ggboxplot(emb_df, x = "condition", y = "emb_1", add = "point", order = c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "embodiment1.png")

###### embodiment 2 ###### 
bxp <- ggboxplot(emb_df, x = "condition", y = "emb_2", add = "point", order = c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "embodiment2.png")



###### embodiment 3 ###### 
bxp <- ggboxplot(emb_df, x = "condition", y = "emb_3", add = "point", order = c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "embodiment3.png")

###### embodiment 4 ###### 
bxp <- ggboxplot(emb_df, x = "condition", y = "emb_4", add = "point", order = c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "embodiment4.png")

###### embodiment 5 ###### 
bxp <- ggboxplot(emb_df, x = "condition", y = "emb_5", add = "point", order = c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "embodiment5.png")

###### embodiment 6 ###### 
bxp <- ggboxplot(emb_df, x = "condition", y = "emb_6", add = "point", order = c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "embodiment6.png")



###### ownership average ###### 
bxp <- ggboxplot(emb_df, x = "condition", y = "owner_ave", add = "point", order = c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "ownership.png")

###### agency average ###### 
bxp <- ggboxplot(emb_df, x = "condition", y = "agency_ave", add = "point", order = c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "agency.png")



###### embodiment average ###### 
bxp <- ggboxplot(emb_df, x = "condition", y = "emb_ave", add = "point", order = c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "embodiment_ave.png")

```


## Check assumptions

```{r check assumptions}

######################### check for outliers ######################### 
emb_df %>%
  group_by(condition) %>%
  identify_outliers(emb_ave)

######################### check normality ######################### 
emb_df %>%
  group_by(condition) %>%
  shapiro_test(emb_ave)
ggqqplot(emb_df, "emb_ave", facet.by = "condition")


```


## Fit Model

```{r fit model}

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(data = emb_df, dv = emb_1, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- emb_df %>%
  pairwise_t_test(
    emb_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(emb_1 ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(emb_1 ~ condition)


```

```{r fit model}

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(data = emb_df, dv = emb_2, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- emb_df %>%
  pairwise_t_test(
    emb_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(emb_2 ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(emb_2 ~ condition)


```

```{r fit model}

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(data = emb_df, dv = emb_3, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- emb_df %>%
  pairwise_t_test(
    emb_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(emb_3 ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(emb_3 ~ condition)


```

```{r fit model}

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(data = emb_df, dv = emb_4, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- emb_df %>%
  pairwise_t_test(
    emb_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(emb_4 ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(emb_4 ~ condition)


```

```{r fit model}

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(data = emb_df, dv = emb_5, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- emb_df %>%
  pairwise_t_test(
    emb_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(emb_5 ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(emb_5 ~ condition)


```

```{r fit model}

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(data = emb_df, dv = emb_6, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- emb_df %>%
  pairwise_t_test(
    emb_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(emb_6 ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(emb_6 ~ condition)


```

```{r fit model}

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(data = emb_df, dv = owner_ave, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- emb_df %>%
  pairwise_t_test(
    emb_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(owner_ave ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(owner_ave ~ condition)


```

```{r fit model}

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(data = emb_df, dv = agency_ave, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- emb_df %>%
  pairwise_t_test(
    emb_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(agency_ave ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(agency_ave ~ condition)


```

```{r fit model}

######################### Two-way mixed ANOVA test #########################  
res.aov <- anova_test(data = emb_df, dv = emb_ave, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- emb_df %>%
  pairwise_t_test(
    emb_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(emb_ave ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(emb_ave ~ condition)


```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
