---
title: "p_trust"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analysis script for "

```{r load libraries}
library(readr)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(stats)
library(lme4)
library(dplyr)
library(ez)
library(ltm)
# library(rcompanion)
```


## Extract dataframe from csv file and get (mean, sd) or (mean, se) summary

```{r read csv}

setwd("C:/Users/micha/OneDrive/My_GitHub_Repos/robot-x-ar/data/questionnaire/")
tlx_df <- read_csv("main_form_cleaned.csv")

######################### get mean and sd (or se) ######################### 
tlx_df %>%
  group_by(condition) %>%
  get_summary_stats(tlx_ave, type = "mean_sd")


tlx_dims_df <- data.frame(tlx_df$tlx_mental, tlx_df$tlx_physical, tlx_df$tlx_hurried, 
                          tlx_df$tlx_successful, tlx_df$tlx_hard, tlx_df$tlx_insecure)

######################### calculate Cronbach's Alpha with 95% confidence interval ######################### 
cronbach.alpha(tlx_dims_df, CI=TRUE)


```

## Plots

```{r do plotting}


### tlx_mental ### 
bxp <- ggboxplot(tlx_df, x = "condition", y = "tlx_mental", add = "point", order=c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "tlx_mental.png")

### tlx_physical ### 
bxp <- ggboxplot(tlx_df, x = "condition", y = "tlx_physical", add = "point", order=c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "tlx_physical.png")

### tlx_hurried ### 
bxp <- ggboxplot(tlx_df, x = "condition", y = "tlx_hurried", add = "point", order=c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "tlx_hurried.png")


### tlx_successful ### 
bxp <- ggboxplot(tlx_df, x = "condition", y = "tlx_successful", add = "point", order=c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "tlx_successful.png")

### tlx_hard ### 
bxp <- ggboxplot(tlx_df, x = "condition", y = "tlx_hard", add = "point", order=c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "tlx_hard.png")

### tlx_insecure ### 
bxp <- ggboxplot(tlx_df, x = "condition", y = "tlx_insecure", add = "point", order=c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "tlx_insecure.png")


### tlx_average ### 
bxp <- ggboxplot(tlx_df, x = "condition", y = "tlx_ave", add = "point", order=c("A", "B", "C", "D"))
bxp
ggexport(bxp, filename = "tlx_ave.png")


# tlx_df %>%
#   ggplot( aes(x=condition, y=tlx_ave)) +
#     geom_line() +
#     geom_point()

```


## Check assumptions

```{r check assumptions}

######################### check for outliers ######################### 
tlx_df %>%
  group_by(condition) %>%
  identify_outliers(tlx_ave)

######################### check normality ######################### 
tlx_df %>%
  group_by(condition) %>%
  shapiro_test(tlx_ave)
ggqqplot(tlx_df, "tlx_ave", facet.by = "condition")


```


## Fit Model

```{r fit model}

###### tlx_mental ###### 

res.aov <- anova_test(data = tlx_df, dv = tlx_mental, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- tlx_df %>%
  pairwise_t_test(
    tlx_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(tlx_mental ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(tlx_mental ~ condition)



```

```{r fit model}

###### tlx_physical ###### 

res.aov <- anova_test(data = tlx_df, dv = tlx_physical, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- tlx_df %>%
  pairwise_t_test(
    tlx_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(tlx_physical ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(tlx_physical ~ condition)



```

```{r fit model}

###### tlx_hurried ###### 

res.aov <- anova_test(data = tlx_df, dv = tlx_hurried, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- tlx_df %>%
  pairwise_t_test(
    tlx_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(tlx_hurried ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(tlx_hurried ~ condition)



```

```{r fit model}

###### tlx_successful ###### 

res.aov <- anova_test(data = tlx_df, dv = tlx_successful, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- tlx_df %>%
  pairwise_t_test(
    tlx_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(tlx_successful ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(tlx_successful ~ condition)



```

```{r fit model}

###### tlx_hard ###### 

res.aov <- anova_test(data = tlx_df, dv = tlx_hard, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- tlx_df %>%
  pairwise_t_test(
    tlx_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(tlx_hard ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(tlx_hard ~ condition)



```

```{r fit model}

###### tlx_insecure ###### 

res.aov <- anova_test(data = tlx_df, dv = tlx_insecure, wid = pid, within = condition)
get_anova_table(res.aov)

# pairwise comparisons
pwc <- tlx_df %>%
  pairwise_t_test(
    tlx_ave ~ condition, paired = TRUE,
    p.adjust.method = "bonferroni"
    )
pwc

##### kruskal-wallis test
res.kruskal <- tlx_df %>% kruskal_test(tlx_insecure ~ condition)
res.kruskal

tlx_df %>% kruskal_effsize(tlx_insecure ~ condition)



```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
